name: Deploy to Firebase
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
        
      - name: Verificar Estrutura (DEBUG)
        run: |
          echo "Estrutura de pastas:"
          ls -la
          echo "\nConteúdo do firebase.json:"
          cat firebase.json
          echo "\nConteúdo da public:"
          ls -la public
      
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy \
            --project revisaocicd \
            --token "$FIREBASE_TOKEN" \
            --only hosting
