name: Deploy to Firebase
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy \
            --project "$FIREBASE_PROJECT_ID" \
            --token "$FIREBASE_TOKEN" \
            --only hosting
